// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// "postgres" (default) = server deployment, talks to a real Postgres instance.
// "sqlite" = embedded/Electron desktop build, single local file, no server process.
// See prisma/schema.sqlite.prisma for why the model bodies must stay identical between the two.
const provider = process.env.DB_PROVIDER === "sqlite" ? "sqlite" : "postgres";

export default defineConfig({
  schema: `prisma/schema.${provider}.prisma`,
  migrations: {
    path: `prisma/migrations-${provider}`,
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate/db) needs DDL, so on Postgres it connects as the migrator role via
    // MIGRATE_DATABASE_URL, falling back to DATABASE_URL. Gated on the postgres provider (a stray
    // MIGRATE_DATABASE_URL must never redirect a sqlite command at Postgres) and an empty string is
    // treated as unset. The app runtime never uses this — it builds its own adapter from
    // DATABASE_URL (the least-privilege app role) in src/lib/db.ts.
    url:
      (provider === "postgres" && process.env["MIGRATE_DATABASE_URL"]) ||
      process.env["DATABASE_URL"],
  },
});
